name: Sync Blog Posts

on:
  push:
    branches:
      - main
    paths:
      - "content/**"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to sync blog posts from'
        required: false
        default: 'main'

jobs:
  sync-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install latest ts-node
        run: npm install ts-node @types/node --save-dev

      - name: Debug - List files
        run: ls -R src/scripts

      - name: Install dependencies
        run: |
          npm install
      
      - name: Run sync script
        run: node --loader ts-node/esm src/scripts/syncPosts.ts

